--------------------------------------------------------------------------------
7	prg3.0	enabled	SELECT F.Value FROM ( SELECT D.Value FROM ( ( SELECT A.Value FROM  ( (SELECT Value FROM sde_facts WHERE Item='mode_crs' AND Value = 1 ) AS A JOIN (SELECT Value FROM sde_facts WHERE Item = 'mode_prg' AND ) AS B ) ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_evo_crs' AND Value = 1 ) AS D ) WHERE D.Value = 1 ) AS E JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_evo_crs_counter' AND Value > ( SELECT Value FROM sde_facts WHERE Item = 'evo_crs_counter_max_limit' ) ) AS F	UPDATE sde_facts SET Value = ( SELECT ( ( RANDOM() * 0.99 ) / RANDOM() ) ) WHERE Status = 'applykbrules' AND Item = 'factor_tgt_hdg_err_avg'	Prg3.0 definition. If mode crs, prg and evo are on, and evo counter 1, then create a new random value for factor_tgt_hdg_err_avg.

8	prg3.0	enabled	SELECT F.Value FROM ( SELECT D.Value FROM ( ( SELECT A.Value FROM  ( (SELECT Value FROM sde_facts WHERE Item='mode_crs' AND Value = 1 ) AS A JOIN (SELECT Value FROM sde_facts WHERE Item = 'mode_prg' ) AS B ) ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_evo_crs' AND Value = 1 ) AS D ) WHERE D.Value = 1 ) AS E JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_evo_crs_counter' AND Value = 1 ) AS F	UPDATE sde_mem_facts SET Value = ( SELECT Value FROM sde_facts WHERE Item = 'factor_tgt_hdg_err_avg' ) WHERE Item = 'factor_tgt_hdg_err_avg' AND (SELECT ABS(Value) FROM sde_facts WHERE Item = 'tgt_hdg_err_avg') < (SELECT ABS(Value) FROM sde_mem_facts WHERE Item = 'tgt_hdg_err_avg')	Prg3.0 definition. Replace mem fact factor_tgt_hdg_err_avg with fact factor_tgt_hdg_err_avg if newly calculated tgt_hdg_err_avg is smaller than the old one.

9	prg3.0	enabled	SELECT F.Value FROM ( SELECT D.Value FROM ( ( SELECT A.Value FROM  ( (SELECT Value FROM sde_facts WHERE Item='mode_crs' AND Value = 1 ) AS A JOIN (SELECT Value FROM sde_facts WHERE Item = 'mode_prg' ) AS B ) ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_evo_crs' AND Value = 1 ) AS D ) WHERE D.Value = 1 ) AS E JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_evo_crs_counter' AND Value = ( SELECT Value FROM sde_facts WHERE Item = 'evo_crs_counter_max_limit' ) ) AS F	UPDATE sde_facts SET Value = ( SELECT Value FROM sde_mem_facts WHERE Item = 'factor_tgt_hdg_err_avg' ) WHERE Item = 'factor_tgt_hdg_err_avg' AND (SELECT ABS(Value) FROM sde_mem_facts WHERE Item = 'tgt_hdg_err_avg') < (SELECT ABS(Value) FROM sde_facts WHERE Item = 'tgt_hdg_err_avg')	Prg3.0 definition. Replace fact factor_tgt_hdg_err_avg with mem_fact factor_tgt_hdg_err_avg if newly calculated tgt_hdg_err_avg is bigger than the old one.

11	prg3.0	enabled	SELECT F.Value FROM ( SELECT D.Value FROM ( ( SELECT A.Value FROM  ( (SELECT Value FROM sde_facts WHERE Item='mode_crs' AND Value = 1 ) AS A JOIN (SELECT Value FROM sde_facts WHERE Item = 'mode_prg' ) AS B ) ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_evo_crs' AND Value = 1 ) AS D ) WHERE D.Value = 1 ) AS E JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_evo_crs_counter' AND Value = ( SELECT Value FROM sde_facts WHERE Item = 'evo_crs_counter_max_limit' ) ) AS F	UPDATE sde_mem_facts SET Value = ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_avg' ) WHERE Item = 'tgt_hdg_err_avg' AND (SELECT ABS(Value) FROM sde_facts WHERE Item = 'tgt_hdg_err_avg') < (SELECT ABS(Value) FROM sde_mem_facts WHERE Item = 'tgt_hdg_err_avg')	Prg3.0 definition. Replace mem fact tgt_hdg_err_avg with fact tgt_hdg_err_avg if newly calculated tgt_hdg_err_avg is smaller than the old one.

33	prg6.0	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_wpt' ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_crs' ) AS B ) WHERE A.Value = 1 AND B.Value = 1	UPDATE sde_facts SET Value = round( ( SELECT Value FROM sde_facts WHERE Item = 'leg_rel_equ_brg' ), 0 ) WHERE Status='applykbrules' AND Item = 'tgt_hdg'	Prg6.0 definition. Update tgt hdg with leg_rel_equ_brg data.

45	prg7.0	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_ailer_counter' AND Value > 2	UPDATE sde_facts SET Value = abs( ( ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' ) / ( SELECT Value FROM sde_facts WHERE Item = 'def_div_factor_max_ailer' ) ) * ( SELECT Value FROM sde_facts WHERE Item = 'airspeed' ) ) WHERE Item = 'factor_max_ailer'	Prg7.0 definition. Calculate max ailer deflection based on deviation from tgt hdg and airspeed when ailer counter > 2.

69	prg8.0	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 0	UPDATE sde_facts SET Value = 0 WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_err_cs'	Prg8.0 definition. tgt_hdg_err_cs to zero on mode rudder zero; this leads to avg on mode rudder 0.

73	prg8.0	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = 0 WHERE ( Value < 0 OR Value >= 360 ) AND Status = 'applykbrules' AND Item LIKE '%hdg'	Prg8.0 definition. Set headings into the interval [0,360).

74	prg8.0	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' AND Value > 180 ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) - 360 )  WHERE Status = 'applykbrules' AND Item = 'turn_rel_hdg'	Prg8.0 definition. Recalculate tgt hdg if value is higher than 180 deg.

75	prg8.0	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'hdg' AND Value = ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = 0 WHERE Status = 'applykbrules' AND Item = 'turn_dir_hdg'	Prg8.0 definition. Set turn dir hdg to zero if hdg and tgt hdg are the same.

76	prg8.0	enabled	SELECT C.Value FROM ( ( SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item='mode_rudder' AND Value = 1) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'hdg' AND Value != ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) ) AS B ) WHERE A.Value = 1 ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'turn_rel_hdg' AND Value < 0 ) AS D ) WHERE C.Value = 1	UPDATE sde_facts SET Value = -1 WHERE Status = 'applykbrules' AND Item = 'turn_fac_hdg'	Prg8.0 definition. Set turn factor to -1, indicating that a left side turn will be actuated.

77	prg8.0	enabled	SELECT C.Value FROM ( ( SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'hdg' AND Value != ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) ) AS B ) WHERE A.Value = 1 ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'turn_rel_hdg' AND Value >= 0 ) AS D ) WHERE C.Value = 1	UPDATE sde_facts SET Value = 1 WHERE Status = 'applykbrules' AND Item = 'turn_fac_hdg'	Prg8.0 definition. Set turn factor to 1, indicating that a right side turn will be actuated.

78	prg8.0	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'turn_rel_hdg' ) + ( ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) * ( SELECT Value FROM sde_facts WHERE Item = 'turn_fac_hdg' ) ) ) WHERE Status = 'applykbrules' AND Item = 'turn_res_hdg'	Prg8.0 definition. Intermediate calculation of turn angle.

79	prg8.0	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' AND Value > 180 ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' ) - 360 ) WHERE Status='applykbrules' AND Item = 'turn_res_hdg'	Prg8.0 definition. Final calculation of turn angle.

80	prg8.0	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' AND Value < -180 ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' ) + 360 ) WHERE Status = 'applykbrules' AND Item = 'turn_res_hdg'	Prg8.0 definition. Final calculation of turn angle.

81	prg8.0	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = ( ( ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' ) / ( 180 ) ) * 2 ) WHERE Status = 'applykbrules' AND Item = 'tgt_rudder'	Prg8.0 definition. Assign tgt rudder value.

83	prg8.0	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) WHERE Status = 'applykbrules' AND Item = 'turn_rel_hdg'	Prg8.0 definition. Set turn rel hdg to the value of tgt hdg before transformation.

87	prg8.0	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'bank' AND abs( Value ) <= ( SELECT Value FROM sde_facts WHERE Item = 'max_bank_rudder_t' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_cs' ) + ( SELECT Value FROM sde_facts WHERE Item = 'rudder' ) )  WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_err_cs'	Prg8.0 definition. On mode rudder 1 and bank <= max_bank_rudder_t, increase tgt_hdg_err_cs by adding current rudder Value.

88	prg8.0	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'bank' AND abs( Value ) <= ( SELECT Value FROM sde_facts WHERE Item = 'max_bank_rudder_t' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_cs' ) / ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder_counter' ) )  WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_err_avg'	Prg8.0 definition. On mode rudder 1 and bank <= max_bank_rudder_t, calculate avg.

89	prg8.0	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'bank' AND abs( Value ) <= ( SELECT Value FROM sde_facts WHERE Item = 'max_bank_rudder_t' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_avg' ) * ( SELECT Value FROM sde_facts WHERE Item = 'factor_tgt_hdg_err_avg' ) )  WHERE Status = 'applykbrules' AND Item = 'rudder_t'	Prg8.0 definition. On mode rudder 1 and bank <= max_bank_rudder_t, tgt_hdg_err_avg to rudder_t.

116	prg9.0	enabled	SELECT C.Value FROM ( ( SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_hato' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'groundcontact' AND Value = 1 ) AS B ) WHERE A.Value = 1 AND B.Value = 1 ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'airspeed' AND Value >= ( SELECT Value FROM sde_facts WHERE Item = 'vr' ) ) AS D ) WHERE C.Value = 1 AND D.Value > 0	UPDATE sde_facts SET Value = ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) WHERE Status = 'applykbrules' AND Item = 'tgt_hdg'	Prg9.0 definition. Set tgt hdg on hdg value on airspeed >= vr and while still on ground.

122	prg10.0	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_crs_counter' AND Value >= 1 AND Value <= 2	UPDATE sde_facts SET Value = ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) WHERE Status = 'applykbrules' AND Item = 'tgt_hdg'	Prg10.0 definition. Set tgt hdg = hdg on crs counter = [1,2].
155	prg10.1	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_crs_counter' AND Value >= 1 AND Value <= 2	UPDATE sde_facts SET Value = ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) WHERE Status = 'applykbrules' AND Item = 'tgt_hdg'	Prg10.1 definition. Set tgt hdg = hdg on crs counter = [1,2].

324	prg8.1	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 0	UPDATE sde_facts SET Value = 0 WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_err_cs'	Prg8.1 definition. tgt_hdg_err_cs to zero on mode rudder zero; this leads to avg on mode rudder 0.

327	prg8.1	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = 0 WHERE ( Value < 0 OR Value >= 360 ) AND Status = 'applykbrules' AND Item LIKE '%hdg'	Prg8.1 definition. Set headings into the interval [0,360).

328	prg8.1	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' AND Value > 180 ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) - 360 )  WHERE Status = 'applykbrules' AND Item = 'turn_rel_hdg'	Prg8.1 definition. Recalculate tgt hdg if value is higher than 180 deg.

329	prg8.1	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'hdg' AND Value = ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = 0 WHERE Status = 'applykbrules' AND Item = 'turn_dir_hdg'	Prg8.1 definition. Set turn dir hdg to zero if hdg and tgt hdg are the same.

330	prg8.1	enabled	SELECT C.Value FROM ( ( SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item='mode_rudder' AND Value = 1) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'hdg' AND Value != ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) ) AS B ) WHERE A.Value = 1 ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'turn_rel_hdg' AND Value < 0 ) AS D ) WHERE C.Value = 1	UPDATE sde_facts SET Value = -1 WHERE Status = 'applykbrules' AND Item = 'turn_fac_hdg'	Prg8.1 definition. Set turn factor to -1, indicating that a left side turn will be actuated.

331	prg8.1	enabled	SELECT C.Value FROM ( ( SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'hdg' AND Value != ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) ) AS B ) WHERE A.Value = 1 ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'turn_rel_hdg' AND Value >= 0 ) AS D ) WHERE C.Value = 1	UPDATE sde_facts SET Value = 1 WHERE Status = 'applykbrules' AND Item = 'turn_fac_hdg'	Prg8.1 definition. Set turn factor to 1, indicating that a right side turn will be actuated.

332	prg8.1	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'turn_rel_hdg' ) + ( ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) * ( SELECT Value FROM sde_facts WHERE Item = 'turn_fac_hdg' ) ) ) WHERE Status = 'applykbrules' AND Item = 'turn_res_hdg'	Prg8.1 definition. Intermediate calculation of turn angle.

333	prg8.1	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' AND Value > 180 ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' ) - 360 ) WHERE Status='applykbrules' AND Item = 'turn_res_hdg'	Prg8.1 definition. Final calculation of turn angle.

334	prg8.1	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' AND Value < -180 ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' ) + 360 ) WHERE Status = 'applykbrules' AND Item = 'turn_res_hdg'	Prg8.1 definition. Final calculation of turn angle.

335	prg8.1	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = ( ( ( SELECT Value FROM sde_facts WHERE Item = 'turn_res_hdg' ) / ( 180 ) ) * 2 ) WHERE Status = 'applykbrules' AND Item = 'tgt_rudder'	Prg8.1 definition. Assign tgt rudder value.

336	prg8.1	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) WHERE Status = 'applykbrules' AND Item = 'turn_rel_hdg'	Prg8.1 definition. Set turn rel hdg to the value of tgt hdg before transformation.

340	prg8.1	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'bank' AND abs( Value ) <= ( SELECT Value FROM sde_facts WHERE Item = 'max_bank_rudder_t' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_cs' ) + ( SELECT Value FROM sde_facts WHERE Item = 'tgt_rudder' ) )  WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_err_cs'	Prg8.1 definition. On mode rudder 1 and bank <= max_bank_rudder_t, increase tgt_hdg_err_cs by adding current rudder Value.

341	prg8.1	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'bank' AND abs( Value ) <= ( SELECT Value FROM sde_facts WHERE Item = 'max_bank_rudder_t' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_cs' ) / ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder_counter' ) )  WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_err_avg'	Prg8.1 definition. On mode rudder 1 and bank <= max_bank_rudder_t, calculate avg.

342	prg8.1	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'bank' AND abs( Value ) <= ( SELECT Value FROM sde_facts WHERE Item = 'max_bank_rudder_t' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_avg' ) * ( SELECT Value FROM sde_facts WHERE Item = 'factor_tgt_hdg_err_avg' ) )  WHERE Status = 'applykbrules' AND Item = 'rudder_t'	Prg8.1 definition. On mode rudder 1 and bank <= max_bank_rudder_t, tgt_hdg_err_avg to rudder_t.

360	prg8.1	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = 0 WHERE Status = 'applykbrules' AND Item = 'turn_fac_hdg'	Prg8.1 definition. Rudder actuator signal.

362	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 0	UPDATE sde_facts SET Value = 0 WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_err_cs'	Prg8.3 definition. tgt_hdg_err_cs to zero on mode rudder zero; this leads to avg on mode rudder 0.

365	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1	UPDATE sde_facts SET Value = 0 WHERE ( Value < 0 OR Value >= 360 ) AND Status = 'applykbrules' AND Item LIKE '%hdg'	Prg8.3 definition. Set headings into the interval [0,360).

366	prg8.3	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'bank' AND abs( Value ) <= ( SELECT Value FROM sde_facts WHERE Item = 'max_bank_rudder_t' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_cs' ) + ( SELECT Value FROM sde_facts WHERE Item = 'tgt_rudder' ) )  WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_err_cs'	Prg8.3 definition. On mode rudder 1 and bank <= max_bank_rudder_t, increase tgt_hdg_err_cs by adding current rudder Value.

367	prg8.3	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'bank' AND abs( Value ) <= ( SELECT Value FROM sde_facts WHERE Item = 'max_bank_rudder_t' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_cs' ) / ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder_counter' ) )  WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_err_avg'	Prg8.3 definition. On mode rudder 1 and bank <= max_bank_rudder_t, calculate avg.

368	prg8.3	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_rudder' AND Value = 1 ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'bank' AND abs( Value ) <= ( SELECT Value FROM sde_facts WHERE Item = 'max_bank_rudder_t' ) ) AS B ) WHERE A.Value = 1	UPDATE sde_facts SET Value = ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_err_avg' ) * ( SELECT Value FROM sde_facts WHERE Item = 'factor_tgt_hdg_err_avg' ) )  WHERE Status = 'applykbrules' AND Item = 'rudder_t'	Prg8.3 definition. On mode rudder 1 and bank <= max_bank_rudder_t, tgt_hdg_err_avg to rudder_t.

372	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'hdg' AND ( Value >= 0 AND Value < 90 )	UPDATE sde_facts SET Value = 1 WHERE Status = 'applykbrules' AND Item = 'hdg_quadrant'	Prg8.3 definition. Check if hdg is on q1.

373	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' AND ( Value >= 0 AND Value < 90 )	UPDATE sde_facts SET Value = 1 WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_quadrant'	Prg8.3 definition. Check if tgt hdg is on q1.

374	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'hdg' AND ( Value >= 90 AND Value < 180 )	UPDATE sde_facts SET Value = 2 WHERE Status = 'applykbrules' AND Item = 'hdg_quadrant'	Prg8.3 definition. Check if hdg is on q2.

375	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' AND ( Value >= 90 AND Value < 180 )	UPDATE sde_facts SET Value = 2 WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_quadrant'	Prg8.3 definition. Check if tgt hdg is on q2.

376	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'hdg' AND ( Value >= 180 AND Value < 270 )	UPDATE sde_facts SET Value = 3 WHERE Status = 'applykbrules' AND Item = 'hdg_quadrant'	Prg8.3 definition. Check if hdg is on q3.

377	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' AND ( Value >= 180 AND Value < 270 )	UPDATE sde_facts SET Value = 3 WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_quadrant'	Prg8.3 definition. Check if tgt hdg is on q3.

378	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'hdg' AND ( Value >= 270 AND Value < 360 )	UPDATE sde_facts SET Value = 4 WHERE Status = 'applykbrules' AND Item = 'hdg_quadrant'	Prg8.3 definition. Check if hdg is on q4.

379	prg8.3	enabled	SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' AND ( Value >= 270 AND Value < 360 )	UPDATE sde_facts SET Value = 4 WHERE Status = 'applykbrules' AND Item = 'tgt_hdg_quadrant'	Prg8.3 definition. Check if tgt hdg is on q4.

392	prg8.3	enabled	SELECT C.Value FROM ( SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'hdg_quadrant' ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_quadrant' ) AS B ) WHERE ( A.Value = B.Value ) ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' AND Value > ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) ) AS D WHERE ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) > ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) )	UPDATE sde_facts SET Value = ( ( ( SELECT Value FROM sde_facts WHERE Item = 'max_rudder' ) * ( 1 ) ) * ( ( ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) - ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) ) * ( 1.00 ) ) / ( 90 ) ) ) WHERE Status = 'applykbrules' AND Item = 'tgt_rudder'	Prg8.3 definition. Pos tgt rudder value on hq=tq h<t.

393	prg8.3	enabled	SELECT C.Value FROM ( SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'hdg_quadrant' ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg_quadrant' ) AS B ) WHERE ( A.Value = B.Value ) ) AS C JOIN ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' AND Value < ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) ) AS D WHERE ( ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) < ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) )	UPDATE sde_facts SET Value = ( ( ( SELECT Value FROM sde_facts WHERE Item = 'max_rudder' ) * ( -1 ) ) * ( ( ( ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) - ( SELECT Value FROM sde_facts WHERE Item = 'tgt_hdg' ) ) * ( 1.00 ) ) / ( 90 ) ) ) WHERE Status = 'applykbrules' AND Item = 'tgt_rudder'	Prg8.3 definition. Pos tgt rudder value on hq=tq h>t.

428	prg6.1	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_wpt' ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_crs' ) AS B ) WHERE A.Value = 1 AND B.Value = 1	UPDATE sde_facts SET Value = round( ( SELECT Value FROM sde_facts WHERE Item = 'leg_rel_equ_brg' ), 0 ) WHERE Status='applykbrules' AND Item = 'tgt_hdg'	Prg6.1 definition. Update tgt hdg with leg_rel_equ_brg data.

574	prg6.2	enabled	SELECT A.Value FROM ( ( SELECT Value FROM sde_facts WHERE Item = 'mode_wpt' ) AS A JOIN ( SELECT Value FROM sde_facts WHERE Item = 'mode_crs' OR Item = 'mode_trs' ) AS B ) WHERE A.Value = 1 AND B.Value = 1	UPDATE sde_facts SET Value = round( ( SELECT Value FROM sde_facts WHERE Item = 'leg_rel_equ_brg' ), 0 ) WHERE Status='applykbrules' AND Item = 'tgt_hdg'	Prg6.2 definition. Update tgt hdg with leg_rel_equ_brg data.

633	prg10.2	enabled	SELECT Value FROM sde_facts WHERE Item = 'mode_crs_counter' AND Value >= 1 AND Value <= 2	UPDATE sde_facts SET Value = ( SELECT Value FROM sde_facts WHERE Item = 'hdg' ) WHERE Status = 'applykbrules' AND Item = 'tgt_hdg'	Prg10.2 definition. Set tgt hdg = hdg on crs counter = [1,2].
